---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    keepalived_options:
      - name: log-detail
    keepalived_vrrp_scripts:
      chk_haproxy:
        script: '/usr/bin/pgrep haproxy'
        weight: 2
        interval: 1

    keepalived_vrrp_instances:
      VI_1:
        interface: eth1
        state: MASTER
        priority: 101
        virtual_router_id: 51

        authentication:
          auth_type: PASS
          auth_pass: '4Apr3C*d'

        virtual_ipaddresses:
          - '10.0.0.10/24 dev eth1 label eth1:1'

        track_interfaces:
          - eth0 weight 10

        track_scripts:
          - chk_haproxy

        raw_options:
          - dont_track_primary

  roles:
    - role: ansible-role-keepalived
